//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: proto/pb_comm.proto
namespace PB
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Room")]
  public partial class Room : global::ProtoBuf.IExtensible
  {
    private global::ProtoBuf.IExtension extensionObject;
	global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
     { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    public Room() {}
    
    private int _id = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _plotId = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"plotId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int plotId
    {
      get { return _plotId; }
      set { _plotId = value; }
    }
    private int _state = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"state", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int state
    {
      get { return _state; }
      set { _state = value; }
    }
    private readonly global::System.Collections.Generic.List<PB.Role> _roles = new global::System.Collections.Generic.List<PB.Role>();
    [global::ProtoBuf.ProtoMember(4, Name=@"roles", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<PB.Role> roles
    {
      get { return _roles; }
    }
  
    private int _houseOwnerId = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"houseOwnerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int houseOwnerId
    {
      get { return _houseOwnerId; }
      set { _houseOwnerId = value; }
    }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Role")]
  public partial class Role : global::ProtoBuf.IExtensible
  {
    private global::ProtoBuf.IExtension extensionObject;
	global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
     { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    public Role() {}
    
    private int _id = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _member = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"member", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int member
    {
      get { return _member; }
      set { _member = value; }
    }
    private bool _ready = default(bool);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"ready", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool ready
    {
      get { return _ready; }
      set { _ready = value; }
    }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Task")]
  public partial class Task : global::ProtoBuf.IExtensible
  {
    private global::ProtoBuf.IExtension extensionObject;
	global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
     { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    public Task() {}
    
    private int _id = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Vector3")]
  public partial class Vector3 : global::ProtoBuf.IExtensible
  {
    private global::ProtoBuf.IExtension extensionObject;
	global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
     { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    public Vector3() {}
    
    private float _x = default(float);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float x
    {
      get { return _x; }
      set { _x = value; }
    }
    private float _y = default(float);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float y
    {
      get { return _y; }
      set { _y = value; }
    }
    private float _z = default(float);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"z", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float z
    {
      get { return _z; }
      set { _z = value; }
    }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Entity")]
  public partial class Entity : global::ProtoBuf.IExtensible
  {
    private global::ProtoBuf.IExtension extensionObject;
	global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
     { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    public Entity() {}
    
    private PB.Vector3 _position = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"position", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public PB.Vector3 position
    {
      get { return _position; }
      set { _position = value; }
    }
    private PB.Vector3 _rotation = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"rotation", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public PB.Vector3 rotation
    {
      get { return _rotation; }
      set { _rotation = value; }
    }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Command")]
  public partial class Command : global::ProtoBuf.IExtensible
  {
    private global::ProtoBuf.IExtension extensionObject;
	global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
     { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    public Command() {}
    
    private string _obj = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"obj", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string obj
    {
      get { return _obj; }
      set { _obj = value; }
    }
    private string _cmd = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"cmd", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string cmd
    {
      get { return _cmd; }
      set { _cmd = value; }
    }
    private string _args = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"args", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string args
    {
      get { return _args; }
      set { _args = value; }
    }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TaskProcess")]
  public partial class TaskProcess : global::ProtoBuf.IExtensible
  {
    private global::ProtoBuf.IExtension extensionObject;
	global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
     { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    public TaskProcess() {}
    
    private int _task = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"task", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int task
    {
      get { return _task; }
      set { _task = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _goals = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(2, Name=@"goals", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> goals
    {
      get { return _goals; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _finished = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(3, Name=@"finished", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> finished
    {
      get { return _finished; }
    }
  
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Dress")]
  public partial class Dress : global::ProtoBuf.IExtensible
  {
    private global::ProtoBuf.IExtension extensionObject;
	global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
     { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    public Dress() {}
    
    private int _roleId = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"roleId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int roleId
    {
      get { return _roleId; }
      set { _roleId = value; }
    }
    private int _partId = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"partId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int partId
    {
      get { return _partId; }
      set { _partId = value; }
    }
    private string _equipId = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"equipId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string equipId
    {
      get { return _equipId; }
      set { _equipId = value; }
    }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Branch")]
  public partial class Branch : global::ProtoBuf.IExtensible
  {
    private global::ProtoBuf.IExtension extensionObject;
	global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
     { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    public Branch() {}
    
    private int _roleId = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"roleId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int roleId
    {
      get { return _roleId; }
      set { _roleId = value; }
    }
    private int _branchId = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"branchId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int branchId
    {
      get { return _branchId; }
      set { _branchId = value; }
    }
  }
  
}