//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: proto/Person.proto
namespace proto.Person
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Person")]
  public partial class Person : global::ProtoBuf.IExtensible
  {
    private global::ProtoBuf.IExtension extensionObject;
	global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
     { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    public Person() {}
    
    private string _name = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private int _id = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private Person.Sex _sex = Person.Sex.male;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"sex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(Person.Sex.male)]
    public Person.Sex sex
    {
      get { return _sex; }
      set { _sex = value; }
    }
    private readonly global::System.Collections.Generic.List<string> _friends = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(4, Name=@"friends", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> friends
    {
      get { return _friends; }
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"Sex")]
    public enum Sex
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"male", Value=0)]
      male = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"female", Value=1)]
      female = 1
    }
  
  }
  
}